name: Deploy to Server

on:
  push:
    branches:
      - master
#      - vip

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      # configure SSH connection to server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.MASTER_SERVER_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Set executable permissions for deploy script
        run: |
          ssh ${{ secrets.MASTER_SERVER_USERNAME }}@${{ secrets.MASTER_SERVER_HOST }} "chmod +x ${{ secrets.MASTER_SERVER_PROJECT_PATH }}/.scripts/deploy.sh"

      # Умови деплойменту для різних гілок
#      - name: Deploy to the VIP server
#        if: github.ref == 'refs/heads/vip'
#        run: |
#          ssh user@vip-server "cd /path/to/app && git pull && ./deploy-script.sh"

      - name: Deploy to the Main server
        if: github.ref == 'refs/heads/master'
        run: |
          ssh ${{ secrets.MASTER_SERVER_USERNAME }}@${{ secrets.MASTER_SERVER_HOST }} "cd ${{ secrets.MASTER_SERVER_PROJECT_PATH }} && git pull && .scripts/deploy.sh "